### ISSUE TITLE
Reload peer-pods-cm envs in cloud-api-adaptor daemonset

### ISSUE THREAD

**Issue by huoqifeng** [confidential-containers/cloud-api-adaptor#1240]
The cloud-api-adaptor daemonset was launched via: https://github.com/confidential-containers/cloud-api-adaptor/blob/main/entrypoint.sh

Which was defined in daemonset https://github.com/confidential-containers/cloud-api-adaptor/blob/main/install/yamls/caa-pod.yaml and the env comes from: https://github.com/confidential-containers/cloud-api-adaptor/blob/main/install/yamls/caa-pod.yaml#L30

It's common case that the env chanes in `peer-pods-cm` configmap but no cloud-api-adaptor binary changes like, PeerPod image changed, the PeerPod profiles changed etc.

Can we have a way to reload these env and reload it in cloud-api-adaptor with or without recreating the pod? 

Options might be:
- Reload controller like: https://github.com/stakater/Reloader/
- Reload sidecar like vault
- ...

vs

Resume the PeerPod instances after cloud-api-adaptor restarts?

**Comment by bpradipt** [comment]
We should augment the peerpodconfig controller to watch for the configmaps and on any change recreate the daemonset. 
The following code needs to be extended - https://github.com/confidential-containers/cloud-api-adaptor/blob/main/peerpodconfig-ctrl/controllers/peerpodconfig_controller.go#L278

**Comment by jtumber-ibm** [comment]
> We should augment the peerpodconfig controller to watch for the configmaps and on any change recreate the daemonset. The following code needs to be extended - https://github.com/confidential-containers/cloud-api-adaptor/blob/main/peerpodconfig-ctrl/controllers/peerpodconfig_controller.go#L278

That would be distruptive to existing peerpods no? Or is that the appropriate response, if configuration changes remake all the peerpods?

**Comment by bpradipt** [comment]
Yes, it'll be indeed disruptive. The pods will be recreated as the original pods will go to "error" state (at least that's what I recall).

**Comment by yoheiueda** [comment]
I think the direct cause that triggers pod VM recreation is that failures in some kata agent APIs.

When a kata shim creates a new containers, it calls some long-running requests including WaitProcess, ReadStdout, and ReadStderr. These calls will return with failures when cloud-api-adaptor restarts, since the connection between the kata-shim and the cloud-api-I think the direct cause that triggers pod VM recreation is that failures in some kata agent APIs. When a kata shim creates a new containers, it calls some long-running requests including WaitProcess, ReadStdout, and ReadStderr. These calls will return with failures when cloud-api-adaptor restarts, since the connection between the kata-shim and the cloud-api-adaptor is lost. To avoid this issue, we need to add a retry logic in kata shim.

https://github.com/confidential-containers/cloud-api-adaptor/blob/7322a2ff36d57feec125ea1a4aadde3714c842d8/pkg/util/agentproto/redirector.go#L131

This is just my guess, and there is a possibility that the ttrpc client in kata shim does not return an error, and automatically reconnects to the server when its connection is lost.

Even after we fix the above problem, we still have another fundamental limitation in our design. cloud-api-adaptor does not currently support restarting, since it has on-memory states. The sandboxes map in the cloudService struct manages the mapping between sandboxID and peer pod VM instance. When cloud-api-adaptor restarts, this mapping is lost. When cloud-api-adaptor receives new requests, it cannot forward the requests to an appropriate pod VM.
https://github.com/confidential-containers/cloud-api-adaptor/blob/7322a2ff36d57feec125ea1a4aadde3714c842d8/pkg/adaptor/cloud/types.go#L41

This issue is described here. https://github.com/confidential-containers/cloud-api-adaptor/issues/375#issuecomment-1334894017

**Comment by yoheiueda** [comment]
> shall we choose an approach to reload the configuration for cloud-api-adaptor non-disruptively vs restart cloud-api-adaptor without recreating the PeerPod instance and keep it still running

I think it is better if restarting `cloud-api-adaptor` daemonset is non-disruptive when its configuration is NOT changed.

In the case of configuration changes, it is probably difficult to determine whether existing pod VMs should be recreated or not. For example, if API key is changed, I am not sure how `cloud-api-adaptor` handles existing pod VMs.

**Comment by huoqifeng** [comment]
We talked about an approach on the meeting yesterday. Like below:
Daemonset supports rolling update but it can not guarantee all PeerPods get recreated before move to next nodes upgrade. Maybe it's helpful if we add a [containers postStart hook](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/) to check whether all PeerPods get recreated and running after caa upgraded on one node. In this way, we can avoid the complete down time window on all nodes (caa upgraded but PeerPods instance not recreated yet). Alternative might be [liveness or readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) if the containers lifecycle hooks does not work.

**Comment by jtumber-ibm** [comment]
I think the correct approach here is using a readiness probe. The rolling update will not proceed until the containers are ready.

**Comment by huoqifeng** [comment]
Close it and created https://github.com/confidential-containers/cloud-api-adaptor/issues/1322 for the implementation.
