### ISSUE TITLE
podvm-mkosi: attestation-agent and cdh do not support /run

### ISSUE THREAD

**Issue by mkulke** [confidential-containers/cloud-api-adaptor#1637]
In mkosi podvm images `agent-config.toml` is stored in /run as /etc should be readonly and we modify that file at runtime. however, the path `/etc/agent-config.toml` is hardcoded in guest-components.

We need to find a way to support the file being in a different location. We would fix the issue probably not here but in guest-components. Since this is a peerpod issue it still makes sense to discuss it here

Options that come to mind are:
- supporting an additional path
- supporting an env for the path (so we can point it to /run at build time)
- support an `AA_KBC_PARAMS` env that can somehow be dynamically set via user-data

**Comment by stevenhorsman** [comment]
So longer-term I think the initdata proposal should resolve this, but getting something done to unblock us sounds good.

For the env path - I just want to make sure that I understand the proposal - we set and environment variable e.g. `AGENT_CONFIG_PATH` in the kata-agent systemd service and then modify attestation-agent and cdh logic to instead of checking for `/run/peerpod/daemon.json` and then parsing `/etc/agent-config.toml` to check for `AGENT_CONFIG_PATH` envvar being set and it so then parse that file?

I like it a lot.

**Comment by mkulke** [comment]
>  we set and environment variable e.g. `AGENT_CONFIG_PATH` in the kata-agent systemd service and then modify attestation-agent and cdh logic to instead of checking for `/run/peerpod/daemon.json` and then parsing `/etc/agent-config.toml` to check for `AGENT_CONFIG_PATH` envvar being set and it so then parse that file?

yup, that would be my preferred option. it's a modest change to support changing the path at build time, until the issue is addressed comprehensively w/ init-data.
