### ISSUE TITLE
ttRpc server cleanup on error

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#172]
https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/pkg/adaptor/hypervisor/aws/server.go#L55
https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/pkg/adaptor/hypervisor/ibmcloud/server.go#L70
https://github.com/confidential-containers/cloud-api-adaptor/blob/staging/pkg/adaptor/hypervisor/libvirt/server.go#L57

@littlejawa let's use this issue to track the ttRpc server cleanup

**Comment by bpradipt** [comment]
cc @yoheiueda

**Comment by yoheiueda** [comment]
I guess this issue is related to this. https://github.com/confidential-containers/cloud-api-adaptor/pull/134#discussion_r946501930

I don't remember the reason why `defer` is set later. I think It is OK to set `defer` immediately after allocation.

BTW, there are duplicated code among multiple providers. I am thinking of refactoring provider code to reduce such redundancy among providers.

**Comment by bpradipt** [comment]
> I guess this issue is related to this. [#134 (comment)](https://github.com/confidential-containers/cloud-api-adaptor/pull/134#discussion_r946501930)
> 
@yoheiueda  this is across the providers.

> I don't remember the reason why `defer` is set later. I think It is OK to set `defer` immediately after allocation.
> 
> BTW, there are duplicated code among multiple providers. I am thinking of refactoring provider code to reduce such redundancy among providers.

Agree on the code duplication. Let me know if you need any help with the refactoring.

**Comment by ariel-adam** [comment]
@bpradipt is this issue still relevant or can be closed? 
If it's still relevant to what release do you think we should map it to (mid-November, end-December, mid-February etc...)?

**Comment by bpradipt** [comment]
Currently the code is refactored and this issue is not relevant. Closing this.
