### ISSUE TITLE
Add a builder to create a rhel podvm image

### ISSUE THREAD

**Issue by whitebrandy** [confidential-containers/cloud-api-adaptor#384]
Have the option to create a rhel podvm image as long as a valid rhel cloud image is specified.

**Comment by jtumber-ibm** [comment]
@bpradipt Is it worth looking at making the generation of qcow images a common task (no provider specific). Also relates to #372. 

Should providers like libvirt and ibmcloud (as we also generate the qcow image and then import rather than building the image using a base ibmcloud image) be able to share the code for creating the qcow image?

Will need to consider cross-platform for this too.
