### ISSUE TITLE
Add e2e test for ibmcloud provider

### ISSUE THREAD

**Issue by huoqifeng** [confidential-containers/cloud-api-adaptor#468]
Based on https://github.com/confidential-containers/cloud-api-adaptor/pull/386, add e2e test for ibmcloud provider.

**Comment by jensfr** [comment]
Hey @huoqifeng , I see this is already merged, but because it contributes to our goal for the 0.4.0 release to have a working CI, is it okay to add this issue to the release board for the[ 0.4.0 release?](https://github.com/orgs/confidential-containers/projects/6/views/12) It would basically go directly to 'Done' :-)

**Comment by huoqifeng** [comment]
I'm not sure do we want to add git actions to do this test against IBM Cloud in 0.4.0 release. The git actions are not covered in the PR. @stevenhorsman do you know what's the plan for CI in IBM Cloud?

**Comment by stevenhorsman** [comment]
Hey QiFeng - sorry for the late reply - I don't think we can use git actions at the moment to drive this as we don't have an IBM Cloud account that we can use for open-source. The approach we were suggesting is that we'd run the tests without our team and then share the results to open-source to demonstrate that we have the tests working. This might have to be ad-hoc and manual in the short-term (and I'm not sure if we've even decided on the place we should share them yet), but if we have a nightly run we could automate this.
