### ISSUE TITLE
Add containerd installation to peer pod operator

### ISSUE THREAD

**Issue by stevenhorsman** [confidential-containers/cloud-api-adaptor#570]
The Coco operator has a preinstall `hook` that installs the confidential containers fork of containerd: https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/base/ccruntime.yaml#L85 until the community is able to adopt the image transfer service in containerd 1.7.

We need to have the same feature in the peer pods install manifest so we can offload image pull just to the pod vm.

I'm guessing that this isn't needed for the CRI-O use cases, so it might be something that we add/remove to the cloud provider's specific kustomize?

\cc @bpradipt @jensfr @snir911 @jtumber-ibm

**Comment by snir911** [comment]
For cri-o there's no solution yet, maybe it would be possible just to return it, i don't recall how it worked before, i can verify next week

**Comment by bpradipt** [comment]
> The Coco operator has a preinstall `hook` that installs the confidential containers fork of containerd: https://github.com/confidential-containers/operator/blob/main/config/samples/ccruntime/base/ccruntime.yaml#L85 until the community is able to adopt the image transfer service in containerd 1.7.
> 
> We need to have the same feature in the peer pods operator so we can offload image pull just to the pod vm.
> 
> I'm guessing that this isn't needed for the CRI-O use cases, so it might be something that we add/remove to the cloud provider's specific kustomize?
> 

@stevenhorsman peer-pods can work without custom containerd due to having the proxy. However without using custom containerd, you'll hit the following issue - https://github.com/confidential-containers/cloud-api-adaptor/issues/371

Btw we don't have a separate peer-pods operator. Are you referring to the install manifests for peer-pods under the `install` directory ? 
I'm in agreement that the install manifests should just reuse the operator manifests as much as possible. 

We do have a separate controller which can manage the entire peer-pods configuration including webhook, advertising the peer-pod extended resources etc. It's yet to be integrated with the CoCo operator.

**Comment by stevenhorsman** [comment]
> @stevenhorsman peer-pods can work without custom containerd due to having the proxy. However without using custom containerd, you'll hit the following issue - #371

@bpradipt - yeah - that issue is exactly why I raised this. I'm happy to close this issue as a dup, but from a quick scan it doesn't look like anyone is discussing the way to fix it being to use the CC fork of containerd?

> Btw we don't have a separate peer-pods operator. Are you referring to the install manifests for peer-pods under the `install` directory ? I'm in agreement that the install manifests should just reuse the operator manifests as much as possible.
> We do have a separate controller which can manage the entire peer-pods configuration including webhook, advertising the peer-pod extended resources etc. It's yet to be integrated with the CoCo operator.

Yes - sorry my terminology (and general understanding) is not fantastic!

**Comment by bpradipt** [comment]
CoCo doesn't support CRI-O yet due to not having the image pull support. However for peer-pods we have circumvented the issue using the proxy. 
I think we can separate the deployment manifests for containerd and cri-o. The containerd one will be leveraging the default that is there for the CoCo operator. The cri-o one will be different since it needs a different runtime-payload image as well and doesn't need a pre-install hook.

**Comment by stevenhorsman** [comment]
I think this issue is resolved now we are using the upstream operator
