### ISSUE TITLE
Handling user-data securely for pod VMs

### ISSUE THREAD

**Issue by bpradipt** [confidential-containers/cloud-api-adaptor#740]
The `user-data` is prepared by the `cloud-api-adaptor` container running on the worker node and provided to the confidential VM via config-drive attached to the VM.  This is processed by cloud-init daemon running inside the confidential VM. 
Currently `user-data` is used to provide pod configuration as well as container image registry secrets to the pod VM.

There is a scope of malicious `user-data` being injected into the confidential VM as the `user-data` generation is happening in the worker node which as per the CoCo threat model is untrusted.

In such a scenario how to ensure the `user-data` that is received is expected and not tampered with before being consumed inside the confidential VM ?

One approach is to treat the `user-data` like the Kubernetes manifest data that can also be modified on the worker node and explore if the policy framework introduced by MSFT can be leveraged - https://github.com/confidential-containers/confidential-containers/issues/126

cc @fitzthum @mkulke @yoheiueda @stevenhorsman @surajssd and others for their inputs.

**Comment by mkulke** [comment]
Thanks for picking up the discussion. There are different ways user-data can be provided to a vm, not sure if this distinction is crucial here, but there might be implications:

- a udf-formatted config-drive that's attached and processed up by cloud-init
- an endpoint on the metadata service, most CSPs and openstack's nova provide those

cloud-init itself is very powerful. for the sake of configuring caa's `agent-protocol-forwarder` something like this might be sufficient:

```bash
curl -s -f -H "Metadata:true" "http://169.254.169.254/metadata/instance/compute/userData?api-version=2021-01-01&format=text" 
  | base64 -d > /peerpod/daemon.json
```

In this scenario `agent-protocol-forwarder` will attempt to establish tunnels according to the given [daemon config](https://github.com/confidential-containers/cloud-api-adaptor/blob/87af9b5260e1c034d119a155851357085e5d3176/pkg/adaptor/cloud/cloud.go#L225). This includes mutual TLS, I think.

**Comment by bpradipt** [comment]
I think we can switch to using userData from IMDS instead of using a config-drive. The agent-protocol-forwarder code can be updated to fetch userData from IMDS and parse and validate only the required items (pod IP, mac address etc).

**Comment by yoheiueda** [comment]
@bpradipt

**Comment by yoheiueda** [comment]
> I think we can switch to using userData from IMDS instead of using a config-drive.

@bpradipt could you elaborate on this? Currently, `agent-protocol-forwarder` only consumes the daemon config data. The `cloud-api-adaptor` prepares the data using the `WriteFile` directive in a cloud-init format.

https://github.com/confidential-containers/cloud-api-adaptor/blob/a9941bba4692c22fada21b5b9f70a1986c74690d/pkg/adaptor/cloud/cloud.go#L262-L269

The `cloud-init` program extracts the data either from config drive or metadata service, and writes the content to `/peerpod/daemon.json`. The `agent-protocol-forwader` just opens the file as a regular local file using the path specified in the command line argument.
https://github.com/confidential-containers/cloud-api-adaptor/blob/a9941bba4692c22fada21b5b9f70a1986c74690d/cmd/agent-protocol-forwarder/main.go#L56

So, my understanding is that the current `agent-protocol-forwarder` does not directly loads data from a config drive.

I think both config drive and metadata service are provided by cloud providers, so peer pod VMs can't trust them. We need encryption and/or signatures to validate their content. I think we should not rely on the `cloud-init` program, since it can do anything. But, I don't think there is a meaningful difference between config drive and metadata service as a data source from the perspective of trust model.

I guess I miss some assumption. Is there any mechanism in metadata service that config drive does not provide?

**Comment by bpradipt** [comment]
@yoheiueda, the basic premise is we can't trust the cloud-init program. But we can trust the agent-protocol-forwarder (which should be measured going forward). 

You are right that from a data source perspective getting userdata via IMDS or via config-drive is the same. At least that's my understanding as well.

However the question to answer is whether agent-protocol-forwarder making an outbound request to get the userdata from IMDS is comparatively more secure from a config-drive+cloud-init approach ?  The assumption is that using IMDS approach is comparatively more secure than config-drive+cloud-init approach. We do need to be sure about this assumption, but would love to hear your thoughts.

**Comment by yoheiueda** [comment]
@bpradipt OK, I've got your point.

I agree that we should stop invoking `cloud-init` at pod VM startup. 

I think implementing direct accesses to metadata service and config drive are both possible. I guess metadata service is easier to support than config drive, since metadata service is just an HTTP server, while we need to handle block devices to support config drive.

So, we can support metadata service first, and then optionally support config drive later.

One question is what format we will use in a userdata. We are using the `cloud-init` config format with the `WriteFile` directive as described above. This is specific to cloud-init, but we don't need to rely on it when we implement our own userdata fetcher.

**Comment by mkulke** [comment]
In mkosi & process-user-data we support both the cloud-drive and IMDS endpoints today
